### ISSUE TITLE
AirPlayRoutePickerView Scroll issue IOS

### ISSUE THREAD

**Issue by EArminjon** [MrJai/flutter_to_airplay#15]
Hi,

AirPlayRoutePickerView make serious scroll issue on flutter 2.2.2.
Is it possible to create a method which we can call AirPlay to make the same result without the actual design (Uikit) ?

It's actually a blocking point for deploy a new release for my apps :)

**Comment by MrJai** [comment]
@EArminjon can you share some video, or steps to reproduce the issue?

**Comment by EArminjon** [comment]
Hum, I found that it was maybe a flutter related issue. When displayed your widget (UiKitView) with many ColorFiltered widget performance are bad. 

You can close it.

Is it possible to create a callback instead of a widget to call airplay ?

**Comment by MrJai** [comment]
@EArminjon can you please confirm what values would you like to receive in the callback?

**Comment by EArminjon** [comment]
Hi @MrJai,

I didn't know well Apple but if possible just an empty method to call airplay. A simple method which will open the airplay pop up.

**Comment by MrJai** [comment]
So let's say we have this functionality, then what are you trying to do with this callback, are you trying to add it to onTap of some GestureDetector or onPressed of some button? I am just trying to understand the use case.

**Comment by EArminjon** [comment]
@MrJai Yep, exactly. I will call it through a gesture detector or something like that.

**Comment by MrJai** [comment]
@EArminjon Please check the example project, I added a new example for you to see how you can add custom icons, buttons, labels, or anything over the Airplay and make it work. I hope this will help your use case.

I will close this issue, once you confirm.

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-05 at 18 26 14](https://user-images.githubusercontent.com/3047049/128357676-411ae890-04d7-443b-b917-990fe0771407.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-05 at 18 26 21](https://user-images.githubusercontent.com/3047049/128357694-14515d6e-229a-4306-be94-ccfd2605f242.png)

**Comment by EArminjon** [comment]
@MrJai Ty for your reply,

If I well understand, the tricks is to set transparent color to your main widget and put a custom one above ? 

```dart
 Container(
  width: 44.0,
  height: 44.0,
  child: Stack(
    children: [
      IconButton(
        onPressed: null,
        icon: Icon(Icons.play_arrow),
      ),
      AirPlayRoutePickerView(
        tintColor: Colors.transparent,
        activeTintColor: Colors.transparent,
        backgroundColor: Colors.transparent,
      ),
    ],
  ),
),
```

No way to create a callback like that ? 

```dart
myButton(
  onTap: () {
      FlutterAirPlay.open();
    };
  child: Icon(Icons.audio),
),

**Comment by MrJai** [comment]
Yes, you are right, you will have to add something over this widget.

I have not found a way to add some call back via method channel, it is only allowing me to add some widget/UIKitView. I will keep looking for this possibility and will surely update here once it is possible.
