### ISSUE TITLE
 null pointer exception on FlutterAVPlayer.swift

### ISSUE THREAD

**Issue by MeshkaniMohammad** [MrJai/flutter_to_airplay#7]
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/MyUserName/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_to_airplay-1.0.3/ios/Classes/FlutterAVPlayer.swift, line 34
Lost connection to device.
```

I just got this error while trying to navigate my video player screen.
I was working with ios Simulator.

**Comment by MrJai** [comment]
Thank you @MeshkaniMohammad. I have submitted a new version with the fix, you can update your package. Please update me so that I can close this issue. Feel free to comment if you see any other issue.

**Comment by MeshkaniMohammad** [comment]
@MrJai Thanks man, you did a great job.
Problem is fixed and we will publish the app for testing
